/**
 * AUTO-GENERATED by scripts/gen-protected-prefixes.mjs — DO NOT EDIT BY HAND.
 *
 * Regenerate with: npm run gen:prefixes
 *
 * This is the single source of truth for protected-URL prefixes, consumed by
 * both src/shared/url-utils.ts (worker side) and src/content/index.ts
 * (content script side), so the two can never drift apart.
 */

export const PROTECTED_URL_PREFIXES: readonly string[] = [
  'chrome://',
  'chrome-extension://',
  'edge://',
  'about:',
  'moz-extension://',
  'brave://',
  'opera://',
  'vivaldi://',
  'file://',
];
