/**
 * AUTO-GENERATED by scripts/gen-protected-prefixes.mjs — DO NOT EDIT BY HAND.
 *
 * Regenerate with: npm run gen:prefixes
 *
 * CONTENT-SCRIPT VARIANT. Deliberately a separate module instance so Rollup
 * inlines the constant into content.js rather than emitting a shared-chunk
 * import (MV3 content scripts are classic scripts and reject `import`).
 * The list itself is authored once, inside the generator.
 */

export const PROTECTED_URL_PREFIXES: readonly string[] = [
  'chrome://',
  'chrome-extension://',
  'edge://',
  'about:',
  'moz-extension://',
  'brave://',
  'opera://',
  'vivaldi://',
  'file://',
];
